/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_snaker_snakerlib_SnakerLibNatives */

#ifndef _Included_xyz_snaker_snakerlib_SnakerLibNatives
#define _Included_xyz_snaker_snakerlib_SnakerLibNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_snaker_snakerlib_SnakerLibNatives
 * Method:    goodbyeWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_snaker_snakerlib_SnakerLibNatives_goodbyeWorld
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
