/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xyz_snaker_natives_SnakerNatives */

#ifndef _Included_xyz_snaker_natives_SnakerNatives
#define _Included_xyz_snaker_natives_SnakerNatives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xyz_snaker_natives_SnakerNatives
 * Method:    forceCrashWindows
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xyz_snaker_natives_SnakerNatives_forceCrashWindows
  (JNIEnv *, jobject);

/*
 * Class:     xyz_snaker_natives_SnakerNatives
 * Method:    assignElevationNoPrompt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xyz_snaker_natives_SnakerNatives_assignElevationNoPrompt
  (JNIEnv *, jobject);

/*
 * Class:     xyz_snaker_natives_SnakerNatives
 * Method:    raiseInternalError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xyz_snaker_natives_SnakerNatives_raiseInternalError
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
