/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bytesnek_hiss_sneaky_SNKR */

#ifndef _Included_bytesnek_hiss_sneaky_SNKR
#define _Included_bytesnek_hiss_sneaky_SNKR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bytesnek_hiss_sneaky_SNKR
 * Method:    goodbyeWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bytesnek_hiss_sneaky_SNKR_goodbyeWorld
(JNIEnv*, jobject);

/*
 * Class:     bytesnek_hiss_sneaky_SNKR
 * Method:    getEarlyMemory
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_bytesnek_hiss_sneaky_SNKR_getEarlyMemory
(JNIEnv*, jobject, jint, jint);

/*
 * Class:     bytesnek_hiss_sneaky_SNKR
 * Method:    deRefNullPtr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bytesnek_hiss_sneaky_SNKR_deRefNullPtr
(JNIEnv*, jobject);

/*
 * Class:     bytesnek_hiss_sneaky_SNKR
 * Method:    breakpointInstance
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_bytesnek_hiss_sneaky_SNKR_breakpointInstance
(JNIEnv*, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
